### ISSUE TITLE
Intergration testing of functionality

### ISSUE THREAD

**Issue by mfrystacky** [bomctl/bomctl#121]
Test each individual command functionality and the chaining of all available commands  the

-     Read SBOMs into the cache
-     Merge SBOMs
-     List SBOMs in the cache
-     Output SBOMs from the cache in a sbom format of your choice
-     Aliasing

**Comment by ashearin** [comment]
Scorecard results:
testscript :5.8
go-cmdtest: 6 (surprisingly)

Without looking at any other options, I'd say testscript is my preference. I'll look around for others though.
