### ISSUE TITLE
Initial Gitlab Client Skeleton and Sbom api Fetch

### ISSUE THREAD

**Issue by ashearin** [bomctl/bomctl#131]
Gitlab api could be leveraged to perform bomctls i/o subcommands like fetch and push. Our users will mainly be using github/gitjab and should be given proper support.

There also ay be future api improvements that allow for importing sboms from gitlab projects.

**Comment by ashearin** [comment]
Changing the scope of this issue to complete two objectives:
- Initial GitLab skeleton
- Fetch sbom endpoint (https://docs.gitlab.com/ee/api/dependency_list_export.html)
Additional issues will be created to fill out the remaining expected functionality

**Comment by lmphil** [comment]
Pull request created to add GitLab Dependency List web API endpoint support to the [xanzy/go-gitlab](https://github.com/xanzy/go-gitlab) package:
https://github.com/xanzy/go-gitlab/pull/2063

**Comment by lmphil** [comment]
Pull request draft created for GitLab fetch: https://github.com/bomctl/bomctl/pull/229

Currently working on unit tests.
