### ISSUE TITLE
Nomination of @pkwiatkowski1 as a maintainer

### ISSUE THREAD

**Issue by idunbarh** [bomctl/bomctl#232]
@pkwiatkowski1 is an active contributor to `bomctl` and while don't have a documented "contributor ladder" he has demonstrated a background in subject and understanding of the codebase. 

I'd like to nomination @pkwiatkowski1 to become a maintainer on this project.

- [Past PRs](https://github.com/bomctl/bomctl/pulls?q=author%3Apkwiatkowski1+is%3Aclosed)

**Comment by jhoward-lm** [comment]
> @eddiezane, @ashearin, and @jhoward-lm the current maintainers, do you have concerns with the addition of @pkwiatkowski1 as a new maintainer on this project?

None at all!

**Comment by ashearin** [comment]
No objections. Fully in support.

**Comment by eddiezane** [comment]
No objections! Thank you for the contributions!
