### ISSUE TITLE
Add make install target to install needed dev tools

### ISSUE THREAD

**Issue by ashearin** [bomctl/bomctl#63]
Thinking something in the spirt of scorecards `make install`, specifically [this](https://github.com/ossf/scorecard/blob/5447253ff192e7e37a7be3b911329c962519aae5/Makefile#L70).

Make a makefile target to install all dev tools to run against contributions prior to commit and update contributing file with expected commands:

https://github.com/bomctl/bomctl/blob/6dc2290fc67682c4143797cd83cb4b3303041a9d/CONTRIBUTING.md?plain=1#L36

Current list (that I found): 
- golangci-lint
- markdownlint-cli2
- yamllint

**Comment by varunpatel-19** [comment]
picking this up (can't assign myself)
