### ISSUE TITLE
Add Github Dependency Review Action

### ISSUE THREAD

**Issue by ashearin** [bomctl/bomctl#72]
https://github.com/marketplace/actions/dependency-review

TLDR: The dependency review action scans your pull requests for dependency changes, and will raise an error if any vulnerabilities or invalid licenses are being introduced. The action is supported by an [API endpoint](https://docs.github.com/en/rest/dependency-graph/dependency-review?apiVersion=2022-11-28) that diffs the dependencies between any two revisions on your default branch.

**Comment by varunpatel-19** [comment]
Working this issue (Don't have permission to assign myself)

**Comment by ashearin** [comment]
Closed in #80
